Controllers/TedarikciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockControl.Models;
using StockControl.Context;
using Sakura.AspNetCore;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace StockControl
{
    public class TedarikciController : Controller
    {
        private readonly BAR_ERPContext _context;

        public TedarikciController(BAR_ERPContext context)
        {
            _context = context;
        }

        // GET: TTedarikciBilgileri
        [Authorize]
        public IActionResult TedarikçiListesi(int? page, int? pageSize, string fieldSearchString, string searchString)
        {
            int no = page ?? 1;
            int size = pageSize ?? 10;
            var result = _context.TTedarikciBilgileri.Where(x => x.SubeNo.ToString() == HttpContext.Session.GetString("SubeNo"));
            if (!String.IsNullOrEmpty(searchString))
            {
                switch (fieldSearchString)
                {
                    case "option1":
                        result = result.Where(s => s.TedarikciNo.Contains(searchString));
                        break;
                    case "option2":
                        result = result.Where(s => s.TedarikciAdi.Contains(searchString));
                        break;
                    case "option3":
                        result = result.Where(s => s.VTCKN.Contains(searchString));
                        break;
                    case "option4":
                        result = result.Where(s => s.Vade.Contains(searchString));
                        break;

                    default:
                        result = _context.TTedarikciBilgileri.Select(x => x);
                        break;
                }
            }
           
                return View(result.ToPagedList(size, no));
            
           
        }

        // GET: TTedarikciBilgileri/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tTedarikciBilgileri = await _context.TTedarikciBilgileri
                .SingleOrDefaultAsync(m => m.TedarikciNo == id);
            if (tTedarikciBilgileri == null)
            {
                return NotFound();
            }

            return View(tTedarikciBilgileri);
        }
        [HttpGet]
        public int GetTedarikciList()
        {
            List<TTedarikciBilgileri> tedarikciListesi = _context.TTedarikciBilgileri.Select(x => x).ToList();
            int say = tedarikciListesi.Select(x => x.TedarikciNo).Count() + 1;
            return say;
        }

        // GET: TTedarikciBilgileri/Create
        [Authorize]
        public IActionResult Create()
        {
            
           
            return View("~/Views/Tedarikci/TedarikciEkle.cshtml");
        }

        // POST: TTedarikciBilgileri/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("SubeNo,TedarikciNo,TedarikciAdi,VTCKN,BankaAdi,IBAN,Vade,OdemeSekli,Ulke,Sehir,Adres,PostaKodu,TelNo,Email,KayitTarihi,DegTarihi,KayitKadi,DegKadi")] TTedarikciBilgileri tTedarikciBilgileri)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tTedarikciBilgileri);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(TedarikçiListesi));
            }
            return View(tTedarikciBilgileri);
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult IsSupplierNameExist(string tedarikciAdi)
        {
            List<string> tedarikciAdiList = (from ua in _context.TTedarikciBilgileri
                                             where ua.SubeNo.ToString()== HttpContext.Session.GetString("SubeNo")
                                             select ua.TedarikciAdi).ToList();


            var validateName = tedarikciAdiList.IndexOf(tedarikciAdi);

            if (validateName != -1)
            {
                return Json($"{tedarikciAdi} kullanılmaktadır.Başka bir isim giriniz.");
            }


            return Json(true);
        }
        // GET: TTedarikciBilgileri/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tTedarikciBilgileri = await _context.TTedarikciBilgileri.SingleOrDefaultAsync(m => m.TedarikciNo == id);
            if (tTedarikciBilgileri == null)
            {
                return NotFound();
            }
            return View(tTedarikciBilgileri);
        }

        // POST: TTedarikciBilgileri/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(string id, [Bind("SubeNo,TedarikciNo,TedarikciAdi,VTCKN,BankaAdi,IBAN,Vade,OdemeSekli,Ulke,Sehir,Adres,PostaKodu,TelNo,Email,KayitTarihi,DegTarihi,KayitKadi,DegKadi")] TTedarikciBilgileri tTedarikciBilgileri)
        {
            if (id != tTedarikciBilgileri.TedarikciNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tTedarikciBilgileri);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TTedarikciBilgileriExists(tTedarikciBilgileri.TedarikciNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(TedarikçiListesi));
            }
            return View(tTedarikciBilgileri);
        }

        // GET: TTedarikciBilgileri/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tTedarikciBilgileri = await _context.TTedarikciBilgileri
                .SingleOrDefaultAsync(m => m.TedarikciNo == id);
            if (tTedarikciBilgileri == null)
            {
                return NotFound();
            }

            return View(tTedarikciBilgileri);
        }

        // POST: TTedarikciBilgileri/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var tTedarikciBilgileri = await _context.TTedarikciBilgileri.SingleOrDefaultAsync(m => m.TedarikciNo == id);
            _context.TTedarikciBilgileri.Remove(tTedarikciBilgileri);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(TedarikçiListesi));
        }

        private bool TTedarikciBilgileriExists(string id)
        {
            return _context.TTedarikciBilgileri.Any(e => e.TedarikciNo == id);
        }


    }
}

Views/Tedarikci/Delete.cshtml
@model StockControl.Models.TTedarikciBilgileri




    <h2 style="text-align:left" class="alert alert-danger">
        Silmek istediğinizden emin misiniz?

    </h2>

    <div>
        <h4>Tedarikçi Bilgileri</h4>
        <hr />
        <div class="container">
            <div class="form-row">
                <div class="col-xs-5">
                    <dl class="dl-horizontal">
                        <dt>
                            Şube No:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.SubeNo)
                        </dd>
                        <dt>
                            Tedarikçi No:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.TedarikciNo)
                        </dd>
                        <dt>
                            Tedarikçi Adı:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.TedarikciAdi)
                        </dd>
                        <dt>
                            Vergi/Kimlik No:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.VTCKN)
                        </dd>
                        <dt>
                            Banka Adı:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.BankaAdi)
                        </dd>
                        <dt>
                            IBAN:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.IBAN)
                        </dd>
                        <dt>
                            Ödeme Vadesi:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Vade)
                        </dd>
                        <dt>
                            Ödeme Şekli:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.OdemeSekli)
                        </dd>
                        <dt>
                            Ülke:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Ulke)
                        </dd>
                        <dt>
                            Şehir:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Sehir)
                        </dd>
                        <dt>
                            Adres:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Adres)
                        </dd>
                        <dt>
                            Posta Kodu:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.PostaKodu)
                        </dd>
                        <dt>
                            Tel No:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.TelNo)
                        </dd>
                        <dt>
                            Email:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Email)
                        </dd>
                    </dl>
                </div>
                <div class="col-xs-3">
                    <div>
                        <label class="col-form-label">Kayıt Oluşturan:</label>
                        @Html.DisplayFor(model => model.KayitKadi)
                    </div>
                    <div>
                        <label class="col-form-label">Kayıt Değiştiren:</label>
                        @Html.DisplayFor(model => model.DegKadi)
                    </div>
                    <div>
                        <label class="col-form-label">Kayıt Tarihi:</label>
                        @Html.DisplayFor(model => model.KayitTarihi)
                    </div>
                    <div>
                        <label class="col-form-label">Değiştirme Tarihi:</label>
                        @Html.DisplayFor(model => model.DegTarihi)
                    </div>
                </div>
            </div>
        </div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="TedarikciNo" />
            <input type="submit" value="Sil" class="btn btn-danger" />
            <a asp-action="TedarikçiListesi" class="btn btn-warning">Tedarikçi Listesi</a>
        </form>
    </div>

Views/Tedarikci/Details.cshtml
@model StockControl.Models.TTedarikciBilgileri



    <h2>
        Tedarikçi Detaylar

    </h2>


    <h4>Tedarikçi Bilgileri</h4>
    <hr />
    <div class="container">
        <div class="form-row">
            <div class="col-xs-5">
                <dl class="dl-horizontal">
                    <dt>
                        Şube No:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.SubeNo)
                    </dd>
                    <dt>
                        Tedarikçi No:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TedarikciNo)
                    </dd>
                    <dt>
                        Tedarikçi Adı:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TedarikciAdi)
                    </dd>
                    <dt>
                        Vergi/Kimlik No:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.VTCKN)
                    </dd>
                    <dt>
                        Banka Adı:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.BankaAdi)
                    </dd>
                    <dt>
                        IBAN:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.IBAN)
                    </dd>
                    <dt>
                        Ödeme Vadesi:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Vade)
                    </dd>
                    <dt>
                        Ödeme Şekli:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.OdemeSekli)
                    </dd>

                    <dt>
                        Ülke:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Ulke)
                    </dd>
                    <dt>
                        Şehir:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Sehir)
                    </dd>
                    <dt>
                        Adres:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Adres)
                    </dd>
                    <dt>
                        Posta Kodu:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PostaKodu)
                    </dd>
                    <dt>
                        Tel No:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TelNo)
                    </dd>
                    <dt>
                        Email:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                </dl>
            </div>
            <div class="col-xs-3">
                <div>
                    <label class="col-form-label">Kayıt Oluşturan:</label>
                    @Html.DisplayFor(model => model.KayitKadi)
                </div>
                <div>
                    <label class="col-form-label">Kayıt Değiştiren:</label>
                    @Html.DisplayFor(model => model.DegKadi)
                </div>
                <div>
                    <label class="col-form-label">Kayıt Tarihi:</label>
                    @Html.DisplayFor(model => model.KayitTarihi)
                </div>
                <div>
                    <label class="col-form-label">Değiştirme Tarihi:</label>
                    @Html.DisplayFor(model => model.DegTarihi)
                </div>
            </div>
        </div>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.TedarikciNo" class="btn btn-success">Düzenle</a>
        <a asp-controller="Tedarikci" asp-action="TedarikçiListesi" class="btn btn-warning">Tedarikçi Listesi</a>
    </div>

Views/Tedarikci/TedarikçiListesi.cshtml
@model Sakura.AspNetCore.IPagedList<StockControl.Models.TTedarikciBilgileri>




    <h2>Tedarikçi Listesi</h2>

    <div class="container" style="margin-bottom:15px">
        <div class="col-xs-2">
            <a asp-action="Create" class="btn btn-primary">Yeni Tedarikçi Ekle</a>
        </div>
    </div>
    <form asp-action="TedarikçiListesi">
        <input type="text" name="fieldSearchString" value="option1" id="fieldSearchString" hidden />
        <div class="container">
            <div class="col-xs-2">
                <select type="text" class="form-control" id="select-searchField" onchange="ToController()" placeholder="Arama Alanı seçiniz...">
                    <option value="option1" selected>Tedarikçi No</option>
                    <option value="option2">Tedarikçi Adı</option>
                    <option value="option3">Vergi/Kimlik No</option>
                    <option value="option4">Ödeme Vadesi</option>

                </select>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control" name="searchString" placeholder="Arama..." />
            </div>
            <div class="col-xs-2">
                <input class="btn btn-success" value="Ara" type="submit" />
            </div>

        </div>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Tedarikçi No
                </th>
                <th>
                    Tedarikçi Adı
                </th>
                <th>
                    Vergi/Kimlik No
                </th>

                <th>
                    Ödeme Vadesi
                </th>

                <th>
                    Telefon
                </th>
                <th>
                    Email
                </th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TedarikciNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TedarikciAdi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VTCKN)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Vade)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.TelNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>

                    <td>
                        <a asp-action="Edit" class="btn btn-success" asp-route-id="@item.TedarikciNo">Güncelle</a>
                        <a asp-action="Details" class="btn btn-info" asp-route-id="@item.TedarikciNo">Detaylar</a>
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.TedarikciNo">Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <pager />

    <script>
        function ToController() {
            $("#fieldSearchString").val($("#select-searchField").val());

        }
    </script>