Controllers/SubeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockControl.Models;
using StockControl.Context;
using Sakura.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace StockControl.Controllers
{
    public class SubeController : Controller
    {
        private readonly BAR_ERPContext _context;

        public SubeController(BAR_ERPContext context)
        {
            _context = context;
        }



        // GET: Sube
        [Authorize]
        public IActionResult SubeListesi(int? page, int? pageSize, string fieldSearchString, string searchString)
        {
            int no = page ?? 1;
            int size = pageSize ?? 10;

            var result = _context.TSubeBilgileri.Select(x => x);

            if (!String.IsNullOrEmpty(searchString))
            {
                switch (fieldSearchString)
                {
                    case "option1":
                        result = result.Where(s => s.SubeNo.ToString().Contains(searchString));
                        break;
                    case "option2":
                        result = result.Where(s => s.SubeAdi.Contains(searchString));
                        break;
                    case "option3":
                        result = result.Where(s => s.Ulke.Contains(searchString));
                        break;
                    case "option4":
                        result = result.Where(s => s.Sehir.Contains(searchString));
                        break;
                    case "option5":
                        result = result.Where(s => s.Adres.Contains(searchString));
                        break;
                    default:
                        result = _context.TSubeBilgileri.Select(x => x);
                        break;
                }
            }
  
            
                return View(result.ToPagedList(size, no));
            
         
        }

        // GET: Sube/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tSubeBilgileri = await _context.TSubeBilgileri
                .SingleOrDefaultAsync(m => m.SubeNo == id);
            if (tSubeBilgileri == null)
            {
                return NotFound();
            }

            return View(tSubeBilgileri);
        }

        // GET: Sube/Create
        [Authorize]
        public IActionResult Create()
        {
            //ViewData["RowNo"] = _context.TSubeBilgileri.Select(x => x.SubeNo).Count()+1;
            return View("~/Views/Sube/SubeEkle.cshtml");
        }

        // POST: Sube/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("SubeNo,SubeAdi,Ulke,Sehir,Adres,PostaKodu,TelNo,Email,KayitTarihi,DegTarihi,KayitKadi,DegKadi")] TSubeBilgileri tSubeBilgileri)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tSubeBilgileri);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(SubeListesi));
            }
            return View(tSubeBilgileri);
        }

        [HttpPost]
        public int CountSubeNo([FromBody]TSubeBilgileri su)
        {
            int count = _context.TSubeBilgileri.Count(x => x.Ulke == su.Ulke) + 1;
            return count;
        }


        // GET: Sube/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["RowNo"] = _context.TSubeBilgileri.Select(x => x.SubeNo).Count() + 1;
            if (id == null)
            {
                return NotFound();
            }

            var tSubeBilgileri = await _context.TSubeBilgileri.SingleOrDefaultAsync(m => m.SubeNo == id);
            if (tSubeBilgileri == null)
            {
                return NotFound();
            }
            return View(tSubeBilgileri);
        }

        // POST: Sube/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("SubeNo,SubeAdi,Ulke,Sehir,Adres,PostaKodu,TelNo,Email,KayitTarihi,DegTarihi,KayitKadi,DegKadi")] TSubeBilgileri tSubeBilgileri)
        {
            if (id != tSubeBilgileri.SubeNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tSubeBilgileri);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TSubeBilgileriExists(tSubeBilgileri.SubeNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(SubeListesi));
            }
            return View(tSubeBilgileri);
        }

        // GET: Sube/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tSubeBilgileri = await _context.TSubeBilgileri
                .SingleOrDefaultAsync(m => m.SubeNo == id);
            if (tSubeBilgileri == null)
            {
                return NotFound();
            }

            return View(tSubeBilgileri);
        }

        // POST: Sube/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tSubeBilgileri = await _context.TSubeBilgileri.SingleOrDefaultAsync(m => m.SubeNo == id);
            _context.TSubeBilgileri.Remove(tSubeBilgileri);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(SubeListesi));
        }

        private bool TSubeBilgileriExists(int id)
        {
            return _context.TSubeBilgileri.Any(e => e.SubeNo == id);
        }
    }
}

Views/Sube/Delete.cshtml
@model StockControl.Models.TSubeBilgileri




    <h2 style="text-align:left" class="alert alert-danger">
        Silmek istediğinizden emin misiniz?

    </h2>
    <div>

        <h4>Şube Bilgileri</h4>
        <hr />
        <div class="container">
            <div class="form-row">
                <div class="col-xs-4">
                    <dl class="dl-horizontal">

                        <dt>
                            Şube No:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.SubeNo)
                        </dd>
                        <dt>
                            Şube Adı:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.SubeAdi)
                        </dd>
                        <dt>
                            Ülke:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Ulke)
                        </dd>
                        <dt>
                            Şehir:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Sehir)
                        </dd>
                        <dt>
                            Adres:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Adres)
                        </dd>
                        <dt>
                            Posta Kodu:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.PostaKodu)
                        </dd>
                        <dt>
                            Tel No:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.TelNo)
                        </dd>
                        <dt>
                            Email:
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Email)
                        </dd>
                    </dl>
                </div>
                <div class="col-xs-3">
                    <div>
                        <label class="col-form-label">Kayıt Oluşturan:</label>
                        @Html.DisplayFor(model => model.KayitKadi)
                    </div>
                    <div>
                        <label class="col-form-label">Kayıt Değiştiren:</label>
                        @Html.DisplayFor(model => model.DegKadi)
                    </div>
                    <div>
                        <label class="col-form-label">Kayıt Tarihi:</label>
                        @Html.DisplayFor(model => model.KayitTarihi)
                    </div>
                    <div>
                        <label class="col-form-label">Değiştirme Tarihi:</label>
                        @Html.DisplayFor(model => model.DegTarihi)
                    </div>
                </div>
                </div>
        </div>

        <form class="container" asp-action="Delete">
            <input type="hidden" asp-for="SubeNo" />
            <input type="submit" value="Sil" class="btn btn-danger" />
            <a asp-controller="Sube" asp-action="SubeListesi" class="btn btn-warning">Şube Listesi</a>
        </form>
    </div>

Views/Sube/Details.cshtml
@model StockControl.Models.TSubeBilgileri




    <h2>Şube Detaylar</h2>


    <h4>Şube Bilgileri</h4>
    <hr />
    <div class="container">
        <div class="form-row">
            <div class="col-xs-4">
                <dl class="dl-horizontal">

                    <dt>
                        Şube No:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.SubeNo)
                    </dd>
                    <dt>
                        Şube Adı:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.SubeAdi)
                    </dd>
                    <dt>
                        Ülke:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Ulke)
                    </dd>
                    <dt>
                        Şehir:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Sehir)
                    </dd>
                    <dt>
                        Adres:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Adres)
                    </dd>
                    <dt>
                        Posta Kodu:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PostaKodu)
                    </dd>
                    <dt>
                        Tel No:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TelNo)
                    </dd>
                    <dt>
                        Email:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                </dl>
            </div>
            <div class="col-xs-3">
                <div>
                    <label class="col-form-label">Kayıt Oluşturan:</label>
                    @Html.DisplayFor(model => model.KayitKadi)
                </div>
                <div>
                    <label class="col-form-label">Kayıt Değiştiren:</label>
                    @Html.DisplayFor(model => model.DegKadi)
                </div>
                <div>
                    <label class="col-form-label">Kayıt Tarihi:</label>
                    @Html.DisplayFor(model => model.KayitTarihi)
                </div>
                <div>
                    <label class="col-form-label">Değiştirme Tarihi:</label>
                    @Html.DisplayFor(model => model.DegTarihi)
                </div>
            </div>
        </div>
        </div>
        <div>
            <a asp-action="Edit" asp-route-id="@Model.SubeNo" class="btn btn-success">Düzenle</a>
            <a asp-controller="Sube" asp-action="SubeListesi" class="btn btn-warning">Şube Listesi</a>
        </div>
  

Views/Sube/Edit.cshtml
@model StockControl.Models.TSubeBilgileri
@using Microsoft.AspNetCore.Http

<form asp-controller="Sube" asp-action="Edit">
    <div class="container">
        <div class="form-row">
            <div class="col-xs-3">
                <h4>Şube Güncelleme</h4>
            </div>
            <div class="float-right">
                <div class="col-xs-2">
                    <label class="col-form-label">Kayıt Oluşturan:</label>
                    <div>@Model.KayitKadi</div>
                    <input asp-for="KayitKadi" class="alert-danger form-control hide" readonly />
                </div>
            </div>
            <div class="float-right">
                <div class="col-xs-2">
                    <label class="col-form-label">Kayıt Değiştiren:</label>
                    <div>@Context.Session.GetString("User")</div>
                    <input asp-for="DegKadi" value="@Context.Session.GetString("User")" class="alert-danger form-control hide" readonly />
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="col-xs-3"></div>
        <div class="float-right">
            <div class="col-xs-2">
                <label class="col-form-label">Kayıt Tarihi:</label>
                <div>@Model.KayitTarihi</div>
                <input asp-for="KayitTarihi" class="alert-danger form-control hide" readonly />
            </div>
            <div class="col-xs-2">
                <label class="col-form-label">Değiştirme Tarihi:</label>
                <div>@DateTime.Now</div>
                <input asp-for="DegTarihi" value="@DateTime.Now" class="alert-danger form-control hide" readonly />
            </div>
        </div>
    </div>
    <hr />


    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container">
        <div class="form-row">
            <div class="col-xs-3">
                <label for="sube-adi" class="col-form-label">Şube Adı:</label>
                <input asp-for="SubeAdi" class="form-control" />
                <span asp-validation-for="SubeAdi" class="text-danger"></span>
            </div>


            <div class="float-right">
                <div class="col-xs-2">
                    <label class="col-form-label">Şube No:</label>
                    <input asp-for="SubeNo" class="alert-danger form-control" readonly />
                </div>
            </div>

            <div class="float-right">
                <div class="col-xs-2">
                    <label class="col-form-label">Kayıt Tarihi:</label>
                    <input asp-for="KayitTarihi" class="alert-danger form-control" readonly />

                    <label class="col-form-label">Değiştirme Tarihi:</label>
                    <input asp-for="DegTarihi" value="@DateTime.Now" class="alert-danger form-control" readonly />
                </div>
            </div>
        </div>
    </div><hr />

    <div class="container">
        <div class="col-xs-3">
            <label class="col-form-label">Ülke:</label>
            <input asp-for="Ulke" class="form-control" readonly />

        </div>
        <div class="col-xs-3">
            <label class="control-label">Şehir:</label>
            <input asp-for="Sehir" class="form-control" />
            <span asp-validation-for="Sehir" class="text-danger"></span>
        </div>
    </div><hr />

    <div class="container">
        <div class="col-xs-6">
            <label class="col-form-label">Adres:</label>
            <textarea asp-for="Adres" class="form-control" rows="5"></textarea>
            <span asp-validation-for="Adres" class="text-danger"></span>
        </div>
    </div><hr />
    <div class="container">
        <div class="col-xs-6">
            <label class="col-form-label">Email:</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div><hr />
    <div class="container">
        <div class="col-xs-3">
            <label class="col-form-label">Tel No:</label>
            <input asp-for="TelNo" class="form-control" maxlength="13" />
            <span asp-validation-for="TelNo" class="text-danger"></span>
        </div>
        <div class="col-xs-3">
            <label class="col-form-label">Posta Kodu:</label>
            <input asp-for="PostaKodu" class="form-control" />
            <span asp-validation-for="PostaKodu" class="text-danger"></span>
        </div>
    </div><hr />

    <div class="container">
        <div class="col-xs-3">
        </div>
        <div class="col-xs-3" style="text-align:right">

            <input type="submit" value="Güncelle" class="btn btn-primary w-75 text-right" />
        </div>
    </div><hr />
    <div class="container">
        <div class="col-xs-3">
        </div>
        <div class="col-xs-3" style="text-align:right">
            <a asp-controller="Sube" asp-action="SubeListesi" class="btn btn-warning" style="margin-top:15px">Şube Listesi</a>
        </div>
    </div><hr />
</form>



@section Scripts
    {
    <script>
        function correctPhoneNo() {
            $("#TelNo").keyup(function () {
                $(this).val($(this).val().replace(/^(\d{3})(\d{3})(\d)+$/, "($1)$2-$3"));
            });

            $("#TelNo").keydown(function (e) {
                var key = e.charCode || e.keyCode || 0;
                // allow backspace, tab, delete, enter, arrows, numbers and keypad numbers ONLY
                // home, end, period, and numpad decimal
                return (
                    key == 8 ||
                    key == 9 ||
                    key == 13 ||
                    key == 46 ||
                    key == 190 ||
                    (key >= 35 && key <= 40) ||
                    (key >= 48 && key <= 57) ||
                    (key >= 96 && key <= 105));
            });
        };
        window.onload(correctPhoneNo());
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


Views/Sube/SubeListesi.cshtml
@model Sakura.AspNetCore.IPagedList<StockControl.Models.TSubeBilgileri>


    <h2>Şube Listesi</h2>

    <div class="container" style="margin-bottom:15px">
        <div class="col-xs-2">
            <a asp-action="Create" class="btn btn-primary">Yeni Şube Ekle</a>
        </div>
    </div>
    <form asp-action="SubeListesi">
        <input type="text" name="fieldSearchString" value="option2" id="fieldSearchString" hidden />
        <div class="container">
            <div class="col-xs-2">
                <select type="text" class="form-control" id="select-searchField" onchange="ToController()" placeholder="Arama Alanı seçiniz...">
                    <option value="option1">Şube No</option>
                    <option value="option2" selected>Şube Adı</option>
                    <option value="option3">Ülke</option>
                    <option value="option4">Şehir</option>
                    <option value="option5">Adres</option>
                </select>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control" name="searchString" placeholder="Arama..." />
            </div>
            <div class="col-xs-2">
                <input class="btn btn-success" value="Ara" type="submit" />
            </div>

        </div>
    </form>
    <table class="table" id="table-grid">
        <thead>
            <tr>
                <th>
                    Şube No
                </th>
                <th>
                    Şube Adı
                </th>
                <th>
                    Ülke
                </th>
                <th>
                    Şehir
                </th>
               
                <th>
                    Telefon
                </th>
                <th>
                    Email
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>

                        @Html.DisplayFor(modelItem => item.SubeNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubeAdi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ulke)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sehir)
                    </td>
                  
                    <td>
                        @Html.DisplayFor(modelItem => item.TelNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.SubeNo" class="btn btn-success">Güncelle</a>
                        <a asp-action="Details" asp-route-id="@item.SubeNo" class="btn btn-info">Detaylar</a>
                        <a asp-action="Delete" asp-route-id="@item.SubeNo" class="btn btn-danger">Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <pager source="@Model" />

    <script>
        function ToController() {
            $("#fieldSearchString").val($("#select-searchField").val());

        }
      
    </script>